package forms;

import Clases.Congreso;
import Clases.Usuario;
import Clases.EmailValidator;
import BD.GestorBaseDatos;
import static BD.GestorBaseDatos.AgregarUsuario;
import Clases.WebValidator;
import Clases.LimiteTextField;
import Clases.LimiteNumeros;
import static forms.frmMain.jdpPrincipal;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.PlainDocument;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Enhu
 */
public class Creacion_usuario extends javax.swing.JInternalFrame {
    
    private static Usuario miUsuario=new Usuario();
    public Vector<Usuario> misUsuarios = new Vector<Usuario>();
    public Vector<Congreso> misCongresos = new Vector<Congreso>();
    static boolean bModificacion=false;
    public Creacion_usuario() {
        initComponents();
        this.setLocation((jdpPrincipal.getWidth()/2-this.getWidth()/2), (jdpPrincipal.getHeight()/2-this.getHeight()/2));
        if (bModificacion){
            txtUsuario.enable(false);
            titulo.setText("Modificacion de Usuario");
            txtUsuario.setText(frmMain.miUsuario.getS_usuario());
            txtNombre.setText(frmMain.miUsuario.getS_nombre());
            txtApellido.setText(frmMain.miUsuario.getS_apellido());
            txtPais.setText(frmMain.miUsuario.getS_pais());
            txtCiudad.setText(frmMain.miUsuario.getS_ciudad());
            txtDireccion.setText(frmMain.miUsuario.getS_direccion());
            txtCodigoPostal.setText(frmMain.miUsuario.getS_cp());
            txtFiliacion.setText(frmMain.miUsuario.getS_filiacion());  
            txtMail.setText(frmMain.miUsuario.getS_mail());  
            txtWeb.setText(frmMain.miUsuario.getS_sitioweb());  
            booleanOIC.setSelected(frmMain.miUsuario.getB_miembro());
            
            
            
            } else {
        
        }        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        booleanOIC = new javax.swing.JCheckBox();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCodigoPostal = new javax.swing.JTextField();
        txtFiliacion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        txtWeb = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmarPassword = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setTitle("Sistema de Gestion de Congresos - Creacion de usuario");
        setPreferredSize(new java.awt.Dimension(800, 600));

        txtUsuario.setDocument(new Clases.LimiteTextField(50));
        txtUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nombre de usuario*");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Apellido*");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nombre*");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Direccion*");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Ciudad");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Código postal*");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("País");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Email*");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Sitio Web");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Filiación*");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Miembro OIC*");

        booleanOIC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        booleanOIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booleanOICActionPerformed(evt);
            }
        });

        txtNombre.setDocument(new Clases.LimiteTextField(38));
        txtNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtApellido.setDocument(new Clases.LimiteTextField(38));
        txtApellido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtPais.setDocument(new Clases.LimiteTextField(20));
        txtPais.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtCiudad.setDocument(new Clases.LimiteTextField(35));
        txtCiudad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDireccion.setDocument(new Clases.LimiteTextField(35));
        txtDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        ((AbstractDocument)txtCodigoPostal.getDocument()).setDocumentFilter(new Clases.LimiteNumeros());
        txtCodigoPostal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCodigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoPostalActionPerformed(evt);
            }
        });

        txtFiliacion.setDocument(new Clases.LimiteTextField(35));
        txtFiliacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Contraseña*");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Confirmar Contraseña*");

        txtMail.setDocument(new Clases.LimiteTextField(38));
        txtMail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });

        txtWeb.setDocument(new Clases.LimiteTextField(38));
        txtWeb.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        titulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titulo.setText("Creacion de usuario");

        txtPassword.setDocument(new Clases.LimiteTextField(10));
        txtPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtConfirmarPassword.setDocument(new Clases.LimiteTextField(10));
        txtConfirmarPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Campos con la leyenda * son obligatorios.\nLa contraseña debe tener minimo 6 caracteres y maximo 10. \nSolo se permiten caracteres alfanumericos, no debe coincidir con el \nnombre de usuario.\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(228, 228, 228)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(290, 290, 290)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(txtConfirmarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(291, 291, 291)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(315, 315, 315)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addGap(0, 0, 0)
                        .addComponent(booleanOIC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(701, 701, 701)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10)
                        .addGap(6, 6, 6)
                        .addComponent(txtFiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11))
                    .addComponent(booleanOIC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
//if(jTextField1.getText().length()>=2) {  
 
 //}        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailActionPerformed

    private void booleanOICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booleanOICActionPerformed

    }//GEN-LAST:event_booleanOICActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCodigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPostalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmLogin Login = new frmLogin();
        String password = new String(txtPassword.getPassword());
        String confirmpassword = new String(txtConfirmarPassword.getPassword());
        EmailValidator emailValidator = new EmailValidator();
        WebValidator webValidator = new WebValidator();
        boolean usuarioexiste=false;
        boolean emailexiste = false;
        
        {    
        try {
            GestorBaseDatos.CargarUsuarios();
        } catch (InstantiationException ex) {
            Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        misUsuarios = GestorBaseDatos.getUsuarios();

   
   for (Usuario i: misUsuarios){
       if(i.getS_usuario().equals(txtUsuario.getText())){
       usuarioexiste = true;
       }else if(i.getS_mail().equals(txtMail.getText())){
       emailexiste = true;    
       }
     } 
   
   
   if(txtUsuario.getText().equals("") || txtNombre.getText().equals("") || txtApellido.getText().equals("") || txtPais.getText().equals("") 
     || txtCiudad.getText().equals("") || txtDireccion.getText().equals("") || txtCodigoPostal.getText().equals("") || txtFiliacion.getText().equals("")){
      JOptionPane.showMessageDialog(null, "No debe dejar campos vacios","Error",JOptionPane.WARNING_MESSAGE); 
   }else if(!password.equals(confirmpassword)){
       JOptionPane.showMessageDialog(null, "La confirmacion y la contraseña inicial no coinciden","Error",JOptionPane.WARNING_MESSAGE);
   }else if(password.length()<6){
       JOptionPane.showMessageDialog(null, "La contraseña debe tener entre minimo 6 y maximo 10 caracteres","Error",JOptionPane.WARNING_MESSAGE);
   }else if(!emailValidator.validate(txtMail.getText().trim())) {
       JOptionPane.showMessageDialog(null, "El email ingresado no es valido","Error",JOptionPane.WARNING_MESSAGE);
   }else if(!webValidator.validate(txtWeb.getText().trim())) {
       JOptionPane.showMessageDialog(null, "La web ingresada no es valida","Error",JOptionPane.WARNING_MESSAGE);
   
   }else  
       
       
       if(bModificacion==false){
           if(usuarioexiste == true){
       JOptionPane.showMessageDialog(null, "El usuario ya existe","Error",JOptionPane.WARNING_MESSAGE);
       usuarioexiste = false;
           }else if(emailexiste == true){
       JOptionPane.showMessageDialog(null, "El email ya existe","Error",JOptionPane.WARNING_MESSAGE);
       emailexiste = false;
           }else{
       
           Usuario nuevoUsuario=new Usuario();
           //nuevoUsuario.setI_Id(4);
           nuevoUsuario.setS_usuario(txtUsuario.getText());
           nuevoUsuario.setS_nombre(txtNombre.getText());
           nuevoUsuario.setS_apellido(txtApellido.getText());
           nuevoUsuario.setS_pais(txtPais.getText());
           nuevoUsuario.setS_ciudad(txtCiudad.getText());
           nuevoUsuario.setS_direccion(txtDireccion.getText());
           nuevoUsuario.setS_cp(txtCodigoPostal.getText());
           nuevoUsuario.setS_filiacion(txtFiliacion.getText());
           nuevoUsuario.setS_password(password);
           nuevoUsuario.setS_mail(txtMail.getText());
           nuevoUsuario.setS_sitioweb(txtWeb.getText());
           nuevoUsuario.setB_miembro(booleanOIC.isSelected());
           
           try {
               GestorBaseDatos.AgregarUsuario(nuevoUsuario);
           } catch (InstantiationException ex) {
               Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IllegalAccessException ex) {
               Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
           } catch (SQLException ex) {
               Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           
           
           
           //miUsuario.agregarUsuario();
           JOptionPane.showMessageDialog(null, "Se ha creado el usuario, por favor entre con su cuenta","Bienvenido",JOptionPane.INFORMATION_MESSAGE);
           
           
           this.dispose();
           frmMain.jdpPrincipal.add(Login);
           Login.show();
               }
           
       }else{
         
           //if(frmLogin.usuarioArroba=false){
           frmMain.getMiUsuario().setS_nombre(txtNombre.getText());
           frmMain.getMiUsuario().setS_apellido(txtApellido.getText());
           frmMain.getMiUsuario().setS_pais(txtPais.getText());
           frmMain.getMiUsuario().setS_ciudad(txtCiudad.getText());
           frmMain.getMiUsuario().setS_direccion(txtDireccion.getText());
           frmMain.getMiUsuario().setS_cp(txtCodigoPostal.getText());
           frmMain.getMiUsuario().setS_filiacion(txtFiliacion.getText());
           frmMain.getMiUsuario().setS_password(password);
           frmMain.getMiUsuario().setS_mail(txtMail.getText());
           frmMain.getMiUsuario().setS_sitioweb(txtWeb.getText());
           frmMain.getMiUsuario().setB_miembro(booleanOIC.isSelected());
           
           try {
               GestorBaseDatos.ModificarUsuario(frmMain.getMiUsuario());
           } catch (InstantiationException ex) {
               Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IllegalAccessException ex) {
               Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
           } catch (SQLException ex) {
               Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           //miUsuario.agregarUsuario();
           JOptionPane.showMessageDialog(null, "Se ha modificado el usuario","Mensaje",JOptionPane.INFORMATION_MESSAGE);
           this.dispose();
         /*}else{
             
           frmMain.getMiUsuario().setS_usuario(txtUsuario.getText());
           frmMain.getMiUsuario().setS_nombre(txtNombre.getText());
           frmMain.getMiUsuario().setS_apellido(txtApellido.getText());
           frmMain.getMiUsuario().setS_pais(txtPais.getText());
           frmMain.getMiUsuario().setS_ciudad(txtCiudad.getText());
           frmMain.getMiUsuario().setS_direccion(txtDireccion.getText());
           frmMain.getMiUsuario().setS_cp(txtCodigoPostal.getText());
           frmMain.getMiUsuario().setS_filiacion(txtFiliacion.getText());
           frmMain.getMiUsuario().setS_password(password);
           frmMain.getMiUsuario().setS_mail(txtMail.getText());
           frmMain.getMiUsuario().setS_sitioweb(txtWeb.getText());
           frmMain.getMiUsuario().setB_miembro(booleanOIC.isSelected());
           System.out.println(frmMain.getMiUsuario().getI_Id());
             try {
                 GestorBaseDatos.ModificarUsuarioArroba(miUsuario);
             } catch (InstantiationException ex) {
                 Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IllegalAccessException ex) {
                 Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(Creacion_usuario.class.getName()).log(Level.SEVERE, null, ex);
             }
               JOptionPane.showMessageDialog(null, "Se ha modificado el usuario","Bienvenido",JOptionPane.INFORMATION_MESSAGE);
           this.dispose();
         
         }*/
         
       }
       //this.dispose();
   
       
        }
             
   
           
   
   
   
   
   
   
   
   
   
   
   
   
   
    }//GEN-LAST:event_jButton1ActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox booleanOIC;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JPasswordField txtConfirmarPassword;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFiliacion;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPais;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtWeb;
    // End of variables declaration//GEN-END:variables
}
