package GuiMail;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import GestionMails.ControladorMail;
import GestionMails.Mail;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Chiara
 */
public class VistaMail extends javax.swing.JInternalFrame implements ActionListener,MouseListener{

    ControladorMail controlador;
    private boolean sonInvitaciones=false;
    //URL url1;
    //URL url2;
    //URL url3;
    //ImageIcon enviando;
    //ImageIcon correoEnviado;
    //ImageIcon correoRechazado;
        

    /**
     * Creates new form Mail
     */
    public VistaMail(ControladorMail controlador) {
       super("Envío De Correo", false, true);
        initComponents();
        this.controlador = controlador;
        this.setBounds(0, 0, 800, 600);
        this.jButton1.addActionListener(this);
        this.jButton2.addActionListener(this);
        this.jButton4.addActionListener(this);
        this.jTextField1.addMouseListener(this);
        this.jTextField2.addMouseListener(this);
        jButton4.setVisible(false);
        this.setVisible(true);
        jLabel4.setForeground(Color.red);
        jLabel6.setForeground(Color.red);
      /*  url1 = this.getClass().getResource("enviando.png");
        url2 = this.getClass().getResource("CorreoEnviado.png");
        url3 = this.getClass().getResource("CorreoRechazado.png");
        enviando=new ImageIcon(url1);
        correoEnviado=new ImageIcon(url2);
        correoRechazado=new ImageIcon(url3);
        */
      
        jButton1.setLocation(10,10);
        
        
        
        jLabel8.setLocation(10,10);
        jLabel8.setVisible(false);
        
        
        

    }

    public void setInvitaciones(boolean invitaciones){
    this.sonInvitaciones=invitaciones;
    }
    public void setJTextField1(String destinatario) {
        this.jTextField1.setText(destinatario);
    }

    public void setJTextField2(String asunto) {
        this.jTextField2.setText(asunto);
    }

    public void setJArea(String cuerpo) {
        this.jTextArea1.setText(cuerpo);
        this.jTextArea1.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setNormalBounds(new java.awt.Rectangle(400, 400, 800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Enviar");
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.setVerifyInputWhenFocusTarget(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Destinatario/s:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Asunto:");

        jTextField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Enviar correo");

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setText("Atras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(190, 190, 190))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(88, 88, 88)))
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(228, 228, 228)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(682, 682, 682))))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jButton4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
public void componentesInvisibles() {
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel5.setVisible(false);
        jList1.setVisible(false);
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        jTextArea1.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jLabel4.setText("");
        jLabel6.setText("");
        jLabel7.setVisible(false);
      
    }

public void componentesVisibles(){
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel5.setVisible(true);
        jList1.setVisible(true);
        jScrollPane1.setVisible(true);
        jScrollPane2.setVisible(true);
        jTextArea1.setVisible(true);
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jLabel2.setForeground(Color.BLACK);
        jLabel1.setForeground(Color.BLACK);

}

    @Override
    public void actionPerformed(ActionEvent e) {
       
      if (e.getSource() == jButton1) {
          if(jButton1.getText().equals("Enviar")){
          Mail mail=controlador.getMail();
            mail.setAsunto(jTextField2.getText());
            mail.setCuerpo(jTextArea1.getText());
            mail.setDestinatario(jTextField1.getText());
           

       if(controlador.sonMails(jTextField1.getText())){
          jLabel1.setForeground(Color.BLACK);
          jLabel4.setText("");
           if(!(jTextField2.getText().equals(""))){ 
           Runnable miRunnable;
            miRunnable = new Runnable() {
                public void run() {

                    
                    componentesInvisibles();
                    setBounds(0,0,800,300);
                    jLabel3.setText("                                                      Enviando...");
                  //  jLabel8.setIcon(enviando);
                    jLabel8.setVisible(true);
                    
                    repaint();
                    getContentPane().repaint();

                    boolean enviado = controlador.enviar();
                    
                    if (enviado) {
                    //    jLabel8.setIcon(correoEnviado);
                        jLabel8.setVisible(true);
                        jLabel3.setText("                                       El mail se ha enviado sastisfactoriamente.");
                        jButton1.setText("Aceptar");
                        jButton1.setVisible(true);
                        //jButton3.setVisible(true);
                         
                    
        
                    } else {
                      //  jLabel8.setIcon(correoRechazado);
                        jLabel8.setVisible(true);
                        jLabel3.setText("     Ha fallado el envio del mail, compruebe su conexion a internet.");
                        //jButton2.setVisible(true);
                        jButton4.setVisible(true);
                        
                        
                    }

                }
            };

            Thread hilo = new Thread(miRunnable);
            hilo.start();
  
     // Crear 2 JPanel para Mail Enviado y Rechazado
     /*
             */}else{
           
            jLabel6.setText("Debe ingresar un asunto");
               
           
           jLabel2.setForeground(Color.red);
           
           }
       
       
       
       }else{
       
       jLabel1.setForeground(Color.red);
       jLabel4.setText("Debe ingresar un mail valido");
       jLabel6.setText("");
       
       
       if(jTextField2.getText().equals("")){
       jLabel2.setForeground(Color.red);
       
        jLabel6.setText("Debe ingresar un asunto");
               
       }else{
       jLabel2.setForeground(Color.BLACK);
       jLabel6.setText("");
       }
       
       }}
          else{ 
              
              if(sonInvitaciones){
              controlador.construirCuerpoEvaluadores(this);
              this.setBounds(0,0,800,600);
              jButton1.setText("Enviar");
              this.componentesVisibles();
              sonInvitaciones=false;
              
              }
              
              else{
              this.setVisible(false);}}
       
       
       
        }

        
        if (e.getSource() == jButton2) {
            this.setVisible(false);
            this.dispose();
            //Pantalla anterior
        }
        //if (e.getSource() == jButton3) {
       //this.setVisible(false);
            
        //}
        if (e.getSource() == jButton4) {
            setBounds(0,0,800,600);
            componentesVisibles();
           jLabel3.setText("");
           jButton4.setVisible(false);
           jLabel8.setVisible(false);
        }
        if(e.getSource()== jTextField1){
            
            jTextField1.setText("");
            
        }
        
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        
    }

    @Override
    public void mousePressed(MouseEvent e) {
    if(e.getSource()==jTextField1){
    jLabel1.setForeground(Color.BLACK);
    jLabel4.setText("");
    
    }
    else{
    jLabel2.setForeground(Color.BLACK);
    jLabel6.setText("");
    }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }

}
